### ISSUE TITLE
Server crash on startup with mna 3.0.0.17

### ISSUE THREAD

**Issue by EtherChicken** [Mithion/Mana-And-Artifice#852]
**Describe the bug**
When attempting to run my minecraft server with the new 3.0.0.17 update, my server crashes with an error log. Still works fine on 3.0.0.15. New server or old server after updating the mna version results in the same crash.
**To Reproduce**
1. Make a minecraft server with forge 47.3.0
2. Download geckolib 4.4.7, curios 5.9.1, and mna 3.0.0.17
3. Attempt to run server- crashes

**Expected behavior**
When launching my server, I would expect it to start as it did with 3.0.0.15, but instead it crashes. Switching the version back to 3.0.0.15 allows the server to run as normal again.

**Version Information:**
 - Mod Version: 1.20.1-3.0.0.17
 - Forge Version  47.3.0

**Crash Report**
Forge server with ONLY mna, geckolib, and curios
https://pastebin.com/hbF9LUqg

Forge server with modpack (I looked over both crash logs and they look the same, still thought I would put this one in too.)
https://pastebin.com/i591rs3L

(sorry for the issue 3 hours after release)

**Comment by Dimmondback** [comment]
Server seems to try rendering something and causing the crash. Here are the logs from the crash:


```
mna-forge-1.20.1-3.0.0.17-all.jar
	Failure message: Mana and Artifice (mna) encountered an error during the complete event phase
		java.lang.NoClassDefFoundError: net/minecraft/client/renderer/blockentity/BlockEntityRenderer
	Mod Version: 3.0.0.17
	Mod Issue URL: https://github.com/Mithion/mna/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraft.client.renderer.blockentity.BlockEntityRenderer
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] {}
	at com.mna.apibridge.APIBridge.onLoadComplete(APIBridge.java:55) ~[mna-forge-1.20.1-3.0.0.17-all.jar%23628!/:3.0.0.17] {re:classloading}
	at com.mna.apibridge.__APIBridge_onLoadComplete_FMLLoadCompleteEvent.invoke(.dynamic) ~[mna-forge-1.20.1-3.0.0.17-all.jar%23628!/:3.0.0.17] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.3.0.jar%23737!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:125) ~[fmlcore-1.20.1-47.3.0.jar%23736!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

```

**Comment by Mithion** [comment]
This has been resolved with 3.0.0.18; apologies!
